#!/bin/bash

syntax()
{
echo "usage: makerepo [action] [action variables]
Note: The [arch] variable will default to 'any' if not specified
Actions:
full - Build full repository 
  Variables: [repolist.file] [repo directory] [arch (i686/x86_64/any)] 
rebuild - Rebuild package
  Variables: [package] [repo directory] [arch (i686/x86_64/any)] 
add - Add package to repository
  Variables: [package] [repo directory] [arch (i686/x86_64/any)] 
addbuilt 
  Variables: [package] [repo directory] 
remove   - Remove package from repository
  Variables: [package] [repo directory]
upload - mirror repo to ftp site
  Variables: [package] [repo directory]" 

exit 0
}

error()
{
if [ "$?" != "0" ]; then
status=Failed
cd ..
exit 1
fi
}

mkdatabase()
{
repo-add flux.db.tar.gz *.xz
}

buildlist()
{
if [ -d $var2 ]; then
	rm -r $var2
	mkdir -p $var2
else
mkdir -p $var2
fi
cd $var2
for i in $(cat $packlist | grep -v "#"); do
error
yaourt -G --noconfirm aur/$i
cd $i
error
sed -i s/^arch=.*/arch=\(\'$arch\'\)/ PKGBUILD
makepkg -sc --noconfirm
error
cd ..
cp -f $i/*pkg.tar.xz ./
rm -rf $i
done
mkdatabase
}

rebuildpackage()
{
echo $var1 $var2
test -d $var2 || $(echo "Specify correct repo directory" && exit &>2)
find $var2 -iname $var1-'[0-9]*' -delete || $(echo "Package not in repository" && exit &>2)
cd $var2
error
yaourt -G --noconfirm aur/$var1
cd $var1
error
sed -i s/^arch=.*/arch=\(\'$arch\'\)/ PKGBUILD
makepkg -sc --noconfirm
error
cd ..
cp -f $var1/*pkg.tar.xz ./
rm -rf $var1
mkdatabase
}

addpackage()
{
test -d $var2 || $(echo "Specify correct repo directory" && exit &>2)
cd $var2
yaourt -G --noconfirm aur/$var1
cd $var1
error
sed -i s/^arch=.*/arch=\(\'$arch\'\)/ PKGBUILD
makepkg -sc --noconfirm
error
cd ..
cp -f $var1/*pkg.tar.xz ./
rm -rf $var1
mkdatabase
}

addbuilt()
{
test -d $var2 || $(echo "Specify correct repo directory" && exit &>2)
cp $var1 $var2	
error
cd $var2
mkdatabase
}

removepackage()
{
test -d $var2 || $(echo "Specify correct repo directory" && exit &>2)
find $var2 -iname $var1-'[0-9]*' -delete || $(echo "Package not in repository" && exit &>2)
cd $var2
mkdatabase
}

syntest()
{
if [ -z $var2 ]; then
echo "Syntax Error"
syntax
fi 
}

var1=$2
var2=$3
packlist=$(pwd)/$var1

if [ "$4" == "i686" ] || [ "$4" == "x86_64" ]; then
	arch=$4
else
	arch=any
fi

uploadrepo()
{
if [ -z $var1 ]; then
	syntax
else
	lftp -e "mirror -R $var1; exit"  fluxrepo
fi
}

case $1 in
	-h		)	syntax ;;
	--help		)	syntax ;;
	help		)	syntax ;;
	full		)	syntest; buildlist ;;
	rebuild		)	syntest; rebuildpackage ;;
	add		)	syntest; addpackage ;;
	addbuilt	)	addbuilt ;;
	remove		)	removepackage ;;
	upload		)	uploadrepo ;;
	*		)	syntax ;;
esac

